[package]
name = "split_rgb"
version = "0.1.0"
edition = "2021"
authors = ["Abhishek Roy <royabhishek77@gmail.com"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.5.0", features = ["cargo"] }
image = "0.24.8"
